Ticket 4347 - log when server requires a restart for a plugin to become active
389ds/389-ds-base pull request #4352
Opened 2020-10-01 01:02 UTC by Firstyear

Bug Description: When testing another feature, user confusion was exprierenced
while enabling a plugin. This was due to a misunderstanding about dynamic
plugins and when and how they take effect.

Fix Description: When dynamic plugins are NOT enabled, and an attempt
is made to enable a plugin, clearly log that we require a restart of
the server for this functionality to become active.

fixes: #4347

Author: William Brown <william@blackhats.net.au>

Review by: ???

2020-10-01 21:38 UTC, droideck requested changes
Looks reasonable and the implementation is good!

One tiny thing, can we have a small test case for the `nsslapd-dynamic-plugins=off` option which checks the message?

2020-10-01 21:49 UTC, Firstyear commented
Sure, that should be easy to do.

2020-10-01 22:26 UTC, Firstyear commented
@droideck Test provided in update, already checked that it works as intended :)

2020-10-02 08:26 UTC, droideck approved these changes
Looks great! Thanks!

2020-10-05 21:26 UTC, mreynolds389 commented
LGTM

2020-10-05 22:14 UTC, Firstyear commented
Double ack! It must be the good code then :)

2020-10-05 22:15 UTC, merged