Issue 4092 - systemd-tmpfiles warnings
389ds/389-ds-base pull request #4494
Opened 2020-12-10 17:07 UTC by mreynolds389

Bug Description:

systemd-tmpfiles warns about legacy paths in our tmpfiles configs.
Using /var/run also introduces a race condition, see the following
issue https://pagure.io/389-ds-base/issue/47429

Fix Description:

Instead of using @localstatedir@/run use @localrundir@ which was
introduced in #850.

Relates: https://github.com/389ds/389-ds-base/issues/766
Fixes: https://github.com/389ds/389-ds-base/issues/4092

2020-12-10 17:10 UTC, mreynolds389 commented
This is a work in progress.  There is still an issue with a weird error as noted in https://github.com/389ds/389-ds-base/issues/4092

    Could not stat /run/user/1000/gvfs: Permission denied.

2020-12-11 01:42 UTC, Firstyear commented
@mreynolds389 I wonder if the error you are seeing is from disk monitoring, because changing from /var/run to /run means we may try to walk the mount points below, and gvfs will put a dynamic mount there from your user session in /run (as /run is shared, not private). So this wouldn't happen on a server because there aren't any gnome virtual filesystem run times to have in /run.

2021-03-25 22:35 UTC, droideck requested changes
Could you please rebase onto the current master this PR? So we can recheck and deal with it :)

2021-03-26 00:52 UTC, mreynolds389 commented
> Could you please rebase onto the current master this PR? So we can recheck and deal with it :)

Done!

2021-10-11 10:40 UTC, vashirov commented
Here's an alternative fix for this. It doesn't affect local prefix installs, but only rpm builds: 
```diff
diff --git a/rpm/389-ds-base.spec.in b/rpm/389-ds-base.spec.in
index 0700e5bc1..347723f61 100644
--- a/rpm/389-ds-base.spec.in
+++ b/rpm/389-ds-base.spec.in
@@ -410,6 +410,9 @@ export XCFLAGS=$RPM_OPT_FLAGS
 
 make %{?_smp_mflags}
 
+# Fix systemd-tmpfiles warning about legacy paths:
+sed -i 's#/var/run#/run#g' %{_builddir}/%{name}-%{version}%{?prerel}/ldap/admin/src/defaults.inf
+
 %install
 rm -rf $RPM_BUILD_ROOT
 
```

2021-10-11 14:21 UTC, mreynolds389 commented
> Here's an alternative fix for this. It doesn't affect local prefix installs, but only rpm builds:
> 
> ```diff
> diff --git a/rpm/389-ds-base.spec.in b/rpm/389-ds-base.spec.in
> index 0700e5bc1..347723f61 100644
> --- a/rpm/389-ds-base.spec.in
> +++ b/rpm/389-ds-base.spec.in
> @@ -410,6 +410,9 @@ export XCFLAGS=$RPM_OPT_FLAGS
>  
>  make %{?_smp_mflags}
>  
> +# Fix systemd-tmpfiles warning about legacy paths:
> +sed -i 's#/var/run#/run#g' %{_builddir}/%{name}-%{version}%{?prerel}/ldap/admin/src/defaults.inf
> +
>  %install
>  rm -rf $RPM_BUILD_ROOT
>  
> ```

This works for me.  We need to address this regardless, and we aren't making any progress otherwise.  So ACK from me

2021-10-11 14:37 UTC, vashirov commented
Ok, thanks. I'll put the change in a separate PR.

2021-10-28 18:49 UTC, merged