Issue 4500 - add cockpit options to dsctl
389ds/389-ds-base pull request #4501
Opened 2020-12-14 19:40 UTC by mreynolds389

Description: 

Allow enabling and disabling cockpit from dsctl.  This also includes firewall operations for the cockpit service.

Fixes: https://github.com/389ds/389-ds-base/issues/4500

Reviewed by: ?

2020-12-14 22:05 UTC, droideck requested changes

2020-12-14 22:05 UTC, droideck commented on src/lib389/lib389/cli_ctl/cockpit.py
> +    rc = os.system(OPEN_CMD)
`os.system()` is deprecated and it's better to use `subprocess.run()` as it's the way to go since Python 3.5 (and helps avoid shell injections)
https://docs.python.org/3/library/subprocess.html#subprocess.run

2020-12-15 02:28 UTC, mreynolds389 commented on src/lib389/lib389/cli_ctl/cockpit.py
> +    rc = os.system(OPEN_CMD)
Oh thanks!  Yes I will rework this...

2020-12-15 02:43 UTC, mreynolds389 commented on src/lib389/lib389/cli_ctl/cockpit.py
> +    rc = os.system(OPEN_CMD)
Changes made, please review @droideck

2020-12-15 10:12 UTC, droideck approved these changes
Looks good to me!

2020-12-15 21:54 UTC, merged