Issue 4169 - UI Migrate checkbox to PF4
389ds/389-ds-base pull request #4769
Opened 2021-05-14 15:40 UTC by jchapma

Description: 	Migrate checkbox from pf3 to pf4
		Button migrations missed in previous PR

		lib/database/ not included in this PR

realtes: https://github.com/389ds/389-ds-base/issues/4169

Reviewed by: ??

2021-05-20 12:36 UTC, jchapma commented on src/cockpit/389-console/src/.vscode/launch.json
> +{
You can ignore this file, I committed it by mistake.

2021-05-24 16:19 UTC, droideck requested changes
A small alignment issue I found:

![iss0](https://user-images.githubusercontent.com/5634892/119376687-89ff1000-bcbc-11eb-97c6-cab5eb833495.png)

2021-06-02 13:47 UTC, droideck commented
Looks good!

Could you please also rebase onto master so we can check that everything is okay
(Because there was an RFE with checkboxes in the advanced Database settings)

2021-06-09 12:45 UTC, jchapma commented
@droideck 

I rebased with master with no issue

2021-06-09 13:15 UTC, mreynolds389 commented
Typo:

```
+++ b/src/cockpit/389-console/src/dsModals.jsx
@@ -674,15 +674,21 @@ export class CreateInstanceModal extends React.Component {
                         </Col>
                     </FormGroup>
                     <hr />
-                    <FormGroup controlId="createDBCheckbox">
-                        <Col componentClass={ControlLabel} sm={5} title="Confirm password.">
+                    <FormGroup controlId="createDatabase">
+                        <Col
+                            componentClass={ControlLabel}
+                            sm={5}
+                            title="Create Database"
+                        >
+                            Create Databse
+                        </Col>
+                        <Col sm={7}>
```

Should be "Create Database", not "Create Datbase"

2021-06-09 14:05 UTC, mreynolds389 commented
Besides the typo in the create instance modal the reset looks good to me...

2021-06-09 14:21 UTC, droideck approved these changes
Besides the typo, @mreynolds389 has mentioned - LGTM too!

2021-06-09 14:27 UTC, merged