Issue 4596 - Build with clang/lld fails when LTO enabled
389ds/389-ds-base pull request #4929
Opened 2021-09-21 21:39 UTC by vashirov

Issue 4596 - Build with clang/lld fails when LTO enabled
 
Bug Description:
Build with clang/lld fails with undefined reference error.
```
ld.lld: error: ./.libs/libslapd.so: undefined reference to __rust_probestack [--no-allow-shlib-undefined]
ld.lld: error: ./.libs/libslapd.so: undefined reference to __muloti4 [--no-allow-shlib-undefined]
```
 
Fix Description:
* Disabled GCC security flags when building with clang.
* lld by default uses xxhash for build ids, which is too small for rpm
(it requires it between 16 and 64 bytes in size), use sha1 instead.
* Switch debug CFLAGS and LDFLAGS to use DWARF4 instead of DWARF5.
* Disable LTO for clang rpm build.
 
Fixes: https://github.com/389ds/389-ds-base/issues/4596
 
Reviewed by: ???

2021-09-22 01:00 UTC, Firstyear approved these changes
Looks good!

2021-09-23 14:44 UTC, vashirov commented
Hmm, it breaks compilation with GCC, I need to revise it.

2022-03-03 23:48 UTC, Firstyear requested changes
Unmarked from approved

2024-01-24 11:25 UTC, closed without merging

2024-11-01 17:01 UTC, vashirov commented
I recreated my fork, and it deleted this PR. I can't reopen it, so I resubmitted it as https://github.com/389ds/389-ds-base/pull/6392