Issue 4962 - Fix various UI bugs part 1
389ds/389-ds-base pull request #4963
Opened 2021-10-26 14:09 UTC by mreynolds389

Fix Description:

Bug 2016022 - Cockpit UI: UI is incorrectly saying "Create the Sub Suffix entry"
Bug 2015951 - Cockpit UI: Database tab ---> Export Database/replicaton
data
Bug 2015221 - Cockpit UI: UX Bugs Server Settings ->Tuning and Limits
Bug 2015139 - Configuration for Import Cache Settings is not saved
Bug 2015127 - No message when configuring Global Database Configuration
Bug 2014924 - Cockpit UI: UX Bugs and other cockpit GUI related defects

relates: https://github.com/389ds/389-ds-base/issues/4962

Reviewed by: ?

2021-10-26 23:52 UTC, droideck requested changes
The rest looks good!

2021-10-26 23:52 UTC, droideck commented on src/cockpit/389-console/src/lib/database/databaseConfig.jsx
> +        this.validateSaveBtn = this.validateSaveBtn.bind(this);
When I go to the Database tab -> Click Global Database Configuration - any update doesn't enable 'Save Config' button... It's always grey.

2021-10-26 23:52 UTC, droideck commented on src/cockpit/389-console/src/lib/server/settings.jsx
>                                      <Grid
Maybe I missed it, but I don't see if it was addressed here:

"[ 3 ] When updating server settings backup directory error is not displayed to the user" from https://bugzilla.redhat.com/show_bug.cgi?id=2014924

2021-10-27 11:43 UTC, jchapma reviewed
2015139
 In Database -> Global Database Configuration. The "Save Config" button doesnt enable when I change any of the settings. 


2014924 - 3
When a non existing back dir is specified by the user an error code is displayed, is it possible to explain the error code.

![Screenshot from 2021-10-27 12-29-44](https://user-images.githubusercontent.com/71395320/139057487-f59b4ced-3412-4a8e-a8c1-27f9466e610c.png)


2014924 - 4
Disk Monitoring Grace period grace period error message says operations error. Could we tell the user that the grace period should be a certain value, like the debug console.

![Screenshot from 2021-10-27 12-35-32](https://user-images.githubusercontent.com/71395320/139058295-8cd721e5-bdf5-40d5-8c23-c70ca0421221.png)

2021-10-28 00:11 UTC, droideck approved these changes
LGTM!

2021-10-28 00:36 UTC, merged