Issue 5043 - BUG - Result must be used compiler warning
389ds/389-ds-base pull request #5045
Opened 2021-12-08 01:35 UTC by Firstyear

Bug Description: Rust 1.57 enforces that Results must be
used, which causes librnsslapd to fail to build

Fix Description: Change how we duplicate the string so
that we don't need the result step.

fixes: https://github.com/389ds/389-ds-base/issues/5043

Author: William Brown <william@blackhats.net.au>

Review by: ???

2021-12-08 07:13 UTC, droideck requested changes
The `CString::from_raw(raw);` error is gone. Nice! But I encounter another error now:

```
 error: use of deprecated associated function `concread::arcache::ARCache::<K, V>::new_size`: please use`ARCacheBuilder` instead
  --> librslapd/src/cache.rs:23:25
   |
23 |         inner: ARCache::new_size(max, read_max),
   |                         ^^^^^^^^
   |
note: the lint level is defined here
  --> librslapd/src/lib.rs:1:9
   |
1  | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(deprecated)]` implied by `#[deny(warnings)]`

error[E0609]: no field `write_inc_or_mod` on type `&concread::cowcell::CowCellReadTxn<CacheStats>`
  --> librslapd/src/cache.rs:61:31
   |
61 |     *write_inc_or_mod = stats.write_inc_or_mod.try_into().unwrap();
   |                               ^^^^^^^^^^^^^^^^ unknown field

For more information about this error, try `rustc --explain E0609`.
error: could not compile `librslapd` due to 2 previous errors
```

On Fedora 34, I've installed rust-std-static-1.57.0-1.fc34.x86_64 and rust-1.57.0-1.fc34.x86_64.
And I've run this (fix me if I'm wrong with the ./configure parameters):

```
autoreconf -fiv
./configure --enable-debug --with-openldap --enable-cmocka --enable-asan --enable-rust
make > /dev/null
```

2021-12-08 20:44 UTC, Firstyear commented
@vashirov I'll fix that in a second commit.

2021-12-08 22:32 UTC, Firstyear commented
https://github.com/389ds/389-ds-base/pull/5047

2021-12-09 06:25 UTC, droideck approved these changes
LGTM! (if https://github.com/389ds/389-ds-base/pull/5047 will be pushed too)

2021-12-09 08:09 UTC, vashirov approved these changes

2021-12-09 22:03 UTC, merged