Issue 5077 - UI - Add retrocl exclude attribute functionality
389ds/389-ds-base pull request #5078
Opened 2021-12-22 13:12 UTC by jchapma

Description: UI needs to be updated to support the exclusion of
attributes from the retro changelog.

Relates: https://github.com/389ds/389-ds-base/issues/5077

Reviewed by: ?

2021-12-22 23:14 UTC, droideck requested changes

2021-12-22 23:14 UTC, droideck commented on src/cockpit/389-console/src/lib/plugins/retroChangelog.jsx
> +        }
Browser crashes here if I try to specify a few attributes.
It happens because '--exclude-attrs' accepts only one value. Also, in the UI, it says 'Exclude attribute' but the field accepts multiple values.

2021-12-22 23:14 UTC, droideck commented on src/cockpit/389-console/src/lib/plugins/retroChangelog.jsx
> +        }
If I try to add a second value here, - it adds an empty item and complains about invalid DN (even if it's valid):

![image](https://user-images.githubusercontent.com/5634892/147165349-bc294c4e-ab99-4485-9760-44d1cd237413.png)

2021-12-22 23:17 UTC, droideck commented on src/cockpit/389-console/src/lib/plugins/retroChangelog.jsx
> +        }
Okay, I see that you've fixed this part in your CLI PR already, so https://github.com/389ds/389-ds-base/pull/5075 should be merged first, I guess

2022-01-05 13:50 UTC, jchapma commented on src/cockpit/389-console/src/lib/plugins/retroChangelog.jsx
> +        }
> Okay, I see that you've fixed this part in your CLI PR already, so #5075 should be merged first, I guess

Hi @droideck 
Yes this UI change is dependant on https://github.com/389ds/389-ds-base/pull/5075, sorry I should have jmentioned that.

2022-01-05 13:54 UTC, jchapma commented on src/cockpit/389-console/src/lib/plugins/retroChangelog.jsx
> +        }
I could add multiple suffixes with no issue, when adding the second suffix did you use the "Create" functionality or hit enter.
![Screenshot from 2022-01-05 13-48-54](https://user-images.githubusercontent.com/71395320/148228845-b959afe1-81e5-40b4-be29-abf750fd2f5c.png)

2022-01-13 17:06 UTC, droideck commented
@jchapma could you please rebase the PR with the new changes from #5075? Then we can check if everything is okay here.

2022-01-13 20:49 UTC, droideck approved these changes
Looks good to me! Great job! Ack

2022-01-17 18:07 UTC, jchapma commented
> Looks good to me! Great job! Ack

Thank you @droideck

2022-01-17 18:08 UTC, merged