Issue 2893 - CLI - dscreate - add options for setting up replication
389ds/389-ds-base pull request #5270
Opened 2022-04-18 20:12 UTC by mreynolds389

Description:

Add options for setting up replication to dscreate

relates: https://github.com/389ds/389-ds-base/issues/2893

2022-04-19 00:14 UTC, Firstyear requested changes, later dismissed

2022-04-19 00:14 UTC, Firstyear commented on src/lib389/lib389/instance/options.py
> +        self._helptext['changelog_max_entries'] = ("The maximum number of entries to keep in the replication changelog (requires that replication is enabled).")
-1 is no limit, defaults to no limit

2022-04-19 00:14 UTC, Firstyear commented
Minor change in text, otherwise looks good :)

2022-04-19 12:57 UTC, mreynolds389 commented on src/lib389/lib389/instance/options.py
> +        self._helptext['changelog_max_entries'] = ("The maximum number of entries to keep in the replication changelog (requires that replication is enabled).")
Fixed

2022-04-19 14:42 UTC, droideck reviewed
The code looks good to me!

One thing only, could you please add a simple test while you're on it?
Something like https://github.com/389ds/389-ds-base/blob/master/dirsrvtests/tests/suites/basic/basic_test.py#L1472

2022-04-19 21:00 UTC, mreynolds389 commented
> The code looks good to me!
> 
> One thing only, could you please add a simple test while you're on it? Something like https://github.com/389ds/389-ds-base/blob/master/dirsrvtests/tests/suites/basic/basic_test.py#L1472

@droideck Done!

2022-04-20 16:11 UTC, droideck approved these changes
Awesome! LGTM!

2022-04-20 23:03 UTC, merged