Issue 4348 - Add tests for dsidm
389ds/389-ds-base pull request #5336
Opened 2022-06-06 18:08 UTC by bsimonova

Description:
Created test for dsidm initialise option.

Relates: https://github.com/389ds/389-ds-base/issues/4348

Reviewed by: ???

2022-06-06 22:16 UTC, droideck approved these changes
LGTM!

2022-06-07 07:31 UTC, vashirov requested changes

2022-06-07 07:31 UTC, vashirov commented on dirsrvtests/tests/suites/clu/dsidm_init_test.py
> +        2  Check there are no sample entries
Missing dots after digits in steps make RST parser sad :(

2022-06-07 07:33 UTC, bsimonova commented on dirsrvtests/tests/suites/clu/dsidm_init_test.py
> +        2  Check there are no sample entries
Oh, right, good catch :D Fixing.

2022-06-07 07:36 UTC, vashirov approved these changes

2022-06-07 07:36 UTC, vashirov commented on dirsrvtests/tests/suites/clu/dsidm_init_test.py
> +        2  Check there are no sample entries
Awesome, thanks! :)

2022-06-07 11:00 UTC, merged