Issue 5440 - memberof is slow on update/fixup if there are several 'g…
389ds/389-ds-base pull request #5455
Opened 2022-09-20 20:03 UTC by tbordaz

…roupattr'

Bug description:
        When there are several groupattr (attr_1, attr_2,..) in memberof config
        To fixup entry 'e1', memberof does an internal search
        "(|(attr_1=e1)(attr_2=e1)...(attr_n=e1))"
        This is not valid regarding membership relation and in
        addition it prevents the server to bypass the filter evaluation.

Fix description:
        To fixup an entry iterate several internal searches
        "(attr_1=e1)" , then "(attr_2=e1)", then "(attr_n=e1)"

relates: #5440

Reviewed by: Pierre Rogier

2022-09-20 20:08 UTC, mreynolds389 commented on ldap/servers/plugins/memberof/memberof.c
> +        /*slapi_log_err(SLAPI_LOG_INFO, MEMBEROF_PLUGIN_SUBSYSTEM, " memberof_call_foreach_dn search \"%s\"\n", filter_str);*/
Should this logging line be removed or set to PLUGIN logging?

2022-09-20 20:14 UTC, mreynolds389 approved these changes
LGTM

2022-09-21 02:53 UTC, droideck approved these changes
Besides the minor ident, looks good to me!

2022-09-21 02:53 UTC, droideck commented on ldap/servers/plugins/memberof/memberof.c
> +                                    memberof_get_plugin_id(), 0);
Just to keep it consistent with the rest of the code, could you, please, fix the indentation here:

```
                            slapi_search_internal_set_pb(search_pb, slapi_sdn_get_dn(config->entryScopes[i]),
                                                         LDAP_SCOPE_SUBTREE, filter_str, 0, 0, 0, 0,
                                                         memberof_get_plugin_id(), 0);
```

2022-09-21 02:53 UTC, droideck commented on ldap/servers/plugins/memberof/memberof.c
> +                        LDAP_SCOPE_SUBTREE, filter_str, 0, 0, 0, 0, memberof_get_plugin_id(), 0);
And here:

```
                slapi_search_internal_set_pb(search_pb, slapi_sdn_get_dn(base_sdn),
                                             LDAP_SCOPE_SUBTREE, filter_str, 0, 0, 0, 0, memberof_get_plugin_id(), 0);
```

2022-09-26 15:13 UTC, progier389 requested changes
Something looks wrong:
slapi_pblock_new is called in a loop but it is freeed only once 
 ( I am also wondereing whether the slapi_pblock_init to reset the pblock in the be loop is correct or not (there me also be a leak here (but not related to this fix))

2022-09-26 16:16 UTC, tbordaz commented
> Something looks wrong: slapi_pblock_new is called in a loop but it is freeed only once ( I am also wondereing whether the slapi_pblock_init to reset the pblock in the be loop is correct or not (there me also be a leak here (but not related to this fix))

Nice catch @progier389 , I updated the PR and will run asan tests.

2022-09-28 20:31 UTC, mreynolds389 commented
@tbordaz - I had an adjustment to your fix because I found it hard to follow the logic of search_pb and how it was being freed.  I think this is cleaner and less error prone.  Thoughts?

```
diff --git a/ldap/servers/plugins/memberof/memberof.c b/ldap/servers/plugins/memberof/memberof.c
index 9a49c1fb6..98955c330 100644
--- a/ldap/servers/plugins/memberof/memberof.c
+++ b/ldap/servers/plugins/memberof/memberof.c
@@ -782,7 +782,6 @@ memberof_call_foreach_dn(Slapi_PBlock *pb __attribute__((unused)), Slapi_DN *sdn
                 }
             }
 
-            search_pb = slapi_pblock_new();
             if (config->entryScopes || config->entryScopeExcludeSubtrees) {
                 if (memberof_entry_in_scope(config, base_sdn)) {
                     /* do nothing, entry scope is spanning
@@ -791,45 +790,44 @@ memberof_call_foreach_dn(Slapi_PBlock *pb __attribute__((unused)), Slapi_DN *sdn
                     for (size_t i = 0; config->entryScopes[i]; i++) {
                         if (slapi_sdn_issuffix(config->entryScopes[i], base_sdn)) {
                             /* Search each include scope */
+                            search_pb = slapi_pblock_new();
                             slapi_search_internal_set_pb(search_pb, slapi_sdn_get_dn(config->entryScopes[i]),
                                                          LDAP_SCOPE_SUBTREE, filter_str, 0, 0, 0, 0,
                                                          memberof_get_plugin_id(), 0);
                             slapi_search_internal_callback_pb(search_pb, callback_data, 0, callback, 0);
+                            slapi_pblock_destroy(search_pb);
                             /* We already did the search for this backend, don't
                              * do it again when we fall through */
                             do_suffix_search = PR_FALSE;
                         }
                     }
                 } else if (!all_backends) {
-                    slapi_pblock_destroy(search_pb);
                     break;
                 } else {
                     /* its ok, goto the next backend */
                     be = slapi_get_next_backend(cookie);
-                    slapi_pblock_destroy(search_pb);
                     continue;
                 }
             }
 
             if (do_suffix_search) {
+                search_pb = slapi_pblock_new();
                 slapi_search_internal_set_pb(search_pb, slapi_sdn_get_dn(base_sdn),
                                              LDAP_SCOPE_SUBTREE, filter_str, 0, 0, 0, 0,
                                              memberof_get_plugin_id(), 0);
                 slapi_search_internal_callback_pb(search_pb, callback_data, 0, callback, 0);
                 slapi_pblock_get(search_pb, SLAPI_PLUGIN_INTOP_RESULT, &rc);
+                slapi_pblock_destroy(search_pb);
                 if (rc != LDAP_SUCCESS) {
-                    slapi_pblock_destroy(search_pb);
                     break;
                 }
             }
 
             if (!all_backends) {
-                slapi_pblock_destroy(search_pb);
                 break;
             }
 
             be = slapi_get_next_backend(cookie);
-            slapi_pblock_destroy(search_pb);
         }
         slapi_ch_free_string(&filter_str);
     }

```

2022-11-10 14:26 UTC, tbordaz commented
> Something looks wrong: slapi_pblock_new is called in a loop but it is freeed only once ( I am also wondereing whether the slapi_pblock_init to reset the pblock in the be loop is correct or not (there me also be a leak here (but not related to this fix))

@progier389 , I changed the logic to get a balanced slapi_pblock_new/slapi_pblock_destroy. Previous patch was leaking but now this change was tested (asan and in production) without leaks.

2022-11-10 15:26 UTC, progier389 approved these changes
LGTM

2022-11-10 15:31 UTC, merged