Issue 5236 - UI - add specialized group edit modal
389ds/389-ds-base pull request #5556
Opened 2022-12-10 16:28 UTC by mreynolds389

Description:

Added a modal for handling groups: viewing, adding and removing members

Revised overall project:

- "Search Base" handling using a label button was not intuitive.  Changed it to a more recognizable href.

- Made table "trash Can" icons visibly clickable

- Edit/add entry wizard, the big red "Empty Value!" label is no longer displayed while you edit the value

relates: https://github.com/389ds/389-ds-base/issues/5236

2022-12-14 02:20 UTC, droideck requested changes
When I try to edit the group with no users, I can click on 'No Members' checkbox and then click on Remove Selected members. And if I do so, all the hell breaks loose:

![image](https://user-images.githubusercontent.com/5634892/207489108-1d5aa621-a486-408f-a6e2-070f7cea5789.png)

2022-12-16 17:21 UTC, mreynolds389 commented
> When I try to edit the group with no users, I can click on 'No Members' checkbox and then click on Remove Selected members. And if I do so, all the hell breaks loose:

Haha, fixed!

2022-12-19 20:00 UTC, droideck commented
Oddly, I still experience the same issue when I try to remove the existing member from the group:

![image](https://user-images.githubusercontent.com/5634892/208509749-2c8cc45a-f3d7-4ea4-91d5-c393bad70c87.png)

2022-12-22 13:13 UTC, mreynolds389 commented
@droideck  sorry I can not reproduce this crash.  I can delete members from groups (all of them) with any issue.

2022-12-22 13:18 UTC, mreynolds389 commented
>  @droideck sorry I can not reproduce this crash. I can delete members from groups (all of them) with any issue.

I still can not reproduce it, but I found what looked like a bug in that code.  So I fixed that,  but like I said I couldn't reproduce it.  Browser issue?  Anyway give it a shot and see how it works for you.

2022-12-22 20:42 UTC, droideck commented
> I still can not reproduce it, but I found what looked like a bug in that code. So I fixed that, but like I said I couldn't reproduce it. Browser issue? Anyway give it a shot and see how it works for you.

That was it! The issue is fixed!

I found another one after I got unblocked (probably a minor clean up issue).
The reproduction steps:

1. Click on Group - then Edit...
2. Add a member using the new interface
3. Click on 'Switch to Generic Interface'
4. Add some new attribute (like description)
5. Then strange things start to happen... (double fields)
![image](https://user-images.githubusercontent.com/5634892/209221891-e9cf7771-cdad-46e4-838c-14cdde6513de.png)
7. And the result LDIF doesn't work:
![image](https://user-images.githubusercontent.com/5634892/209222003-bc113d82-b550-4676-8b38-c35af27ae85c.png)

2022-12-22 22:25 UTC, mreynolds389 commented
> I found another one after I got unblocked (probably a minor clean up issue). The reproduction steps:

Should be fixed now...

2022-12-22 23:46 UTC, droideck approved these changes
All looks great now! Ack.

Happy Holidays, Mark!

2023-01-03 13:37 UTC, merged