Issue 4293 - RFE - CLI - add dsrc options for setting user and group subtrees
389ds/389-ds-base pull request #5626
Opened 2023-02-01 15:29 UTC by mreynolds389

Description: There are customers who do not use "ou=groups" or "ou=people" for theior users and groups.  This RFE allows the user/group RDN to be customized in the .dsrc file

Improved some errors messages, and fixed some pep8 issues

relates: https://github.com/389ds/389-ds-base/issues/4293

2023-02-01 18:38 UTC, droideck requested changes

2023-02-01 18:38 UTC, droideck commented on src/lib389/lib389/cli_ctl/dsrc.py
> +    if args.people_rdn is not None:
Minor thing, CI test `dirsrvtests/tests/suites/clu/dsrc_test.py::test_dsrc` fails here:

```
>       if args.people_rdn is not None:
E       AttributeError: 'FakeArgs' object has no attribute 'people_rdn'
```

2023-02-01 22:19 UTC, mreynolds389 commented on src/lib389/lib389/cli_ctl/dsrc.py
> +    if args.people_rdn is not None:
> Minor thing, CI test `dirsrvtests/tests/suites/clu/dsrc_test.py::test_dsrc` fails here:
> 
> ```
> >       if args.people_rdn is not None:
> E       AttributeError: 'FakeArgs' object has no attribute 'people_rdn'
> ```

@droideck All fixed

2023-02-02 04:10 UTC, droideck approved these changes
LGTM!

2023-02-02 13:13 UTC, merged