Issue 5700 - SRCH performance drop 2.0 vs 1.4
389ds/389-ds-base pull request #5703
Opened 2023-03-17 10:48 UTC by tbordaz

Bug description:
	The commit 40563667e12da3042ea5a0e3771c1e1db1dafa06
	force the evaluation of the filter before returning
	entries. This evaluation can be skipped in case
	of indexed search and filter syntax without OR
	(sr_flags ~SR_FLAG_MUST_APPLY_FILTER_TEST).
	The consequence of the fix is a severe drop of
	search performance.
	The testcase provided with the commit are PASS
	without part of the original fix

Fix description:
	Revert parts of the fix.
	This patch intend to identify new testcase
	that confirm the need to force the evaluation
	of the filter

relates: #5700

Reviewed by:

2023-03-20 00:49 UTC, Firstyear requested changes
I know you want to try to fix this to remove the extra filter tests, but I had to re-add them because they are correct. There were access control bypasses and query corruptions here.

I know it sucks that it affects performance, but setting this flags just undoes all that work I did to fix these to be correct and secure. 

The existing code is *already* the correct set of filter tests and access controls to prevent these bypasses. 

I can't approve this, because it would introduce vulnerabilities. 

If you want to actually improve this, then *remove grok_filter*.

Grok filter is *fundamentally broken* and always forces filter tests even if they are not needed!

2023-03-20 00:49 UTC, Firstyear commented on ldap/servers/slapd/filterentry.c
> -            "⚠️  DANGER ⚠️  - only_check_access mode is BROKEN!!! YOU MUST CHECK ACCESS WITH FILTER MATCHING");
This comment was not incorrect. This is broken, and can lead to access control bypasses.

2023-03-20 00:49 UTC, Firstyear commented on ldap/servers/slapd/back-ldbm/ldbm_search.c
> +                            filter_test = slapi_vattr_filter_test_ext(pb, e->ep_entry, filter_intent, ACL_CHECK_FLAG, 1);
we can't set this. This allows access control bypasses and is a CVE.

2023-03-21 02:22 UTC, Firstyear commented
@tbordaz The change you are proposing here is a straight up security bypass. I can't in good consciousness approve this. 

The comments I have left in filterentry.c are correct - deleting them doesn't change anything. The only_check_access mode is broken because in only_check_access mode it doesn't actually properly apply access controls. 

I don't know why you are so hesitant to listen to me and *just remove grok filter*. 

Look at grok filter. If it sees an OR condition it will always force filter tests. If it sees anything that isn't an EQ filter it forces the test. Look at it https://github.com/389ds/389-ds-base/blob/main/ldap/servers/slapd/back-ldbm/ldbm_search.c#L1307 Anything that returns '0' here forces a filter test. look at how many conditions will have the test forced. 

This one function pretty much prevents us from being able to skip filter tests. Which leaves us having to double filter test - one for the "filter as executed" due to referrals and our optimisation and re-arrangement. And one for access control.

2023-03-21 02:22 UTC, closed without merging

2023-03-21 02:34 UTC, mreynolds389 commented
:-)  In @tbordaz defense, I think this was a WIP PR.  I think Thierry is just making commits as he tests new things.  I don't think he's ignoring your comments.  I think he's just exploring the "space".  Keep in mind he is also working on other things at the same time so he might not be able to respond very quickly.

2023-03-21 09:24 UTC, Firstyear commented
We can't trade performance for security though. That's my major concern here because previously we were exposed to aci bypass as well as query corruption.

I think you really will benefit greatly from looking to drop grok filter.