Issue 5749 - RFE - Allow Account Policy Plugin to handle inactivity and expiration at the same time
389ds/389-ds-base pull request #5750
Opened 2023-05-02 18:25 UTC by mreynolds389

Description:

Currently Account Policy Plugin as a state attribute and alternate state attribute. If the main state attribute is NOT present in the entry then it fails back to the alternate state attribute.

This RFE adds a new setting that tells the plugin to check both state attributes. The purpose of this is for expiration and inactivity, so this is meant to be used when the alternate state attribute is 'passwordExpirationtime'.  So if the main state attribute is OK, it will then check the alternate state attribute for inactivity.

relates: https://github.com/389ds/389-ds-base/issues/5749

2023-05-03 09:37 UTC, tbordaz approved these changes
Nice. LGTM

2023-05-04 04:56 UTC, droideck requested changes
When I try to create an AccPol config entry, the browser crushes for me:

![image](https://user-images.githubusercontent.com/5634892/236115521-e7424650-e1a9-4300-9697-c9f160286789.png)

2023-05-04 04:56 UTC, droideck commented on dirsrvtests/tests/suites/plugins/accpol_check_all_state_attrs_test.py
> +    """
Could be improved :)

2023-05-04 14:53 UTC, mreynolds389 commented on dirsrvtests/tests/suites/plugins/accpol_check_all_state_attrs_test.py
> +    """
Fixed

2023-05-04 14:54 UTC, mreynolds389 commented
> When I try to create an AccPol config entry, the browser crushes for me

All fixed, please review.

2023-05-04 18:18 UTC, droideck approved these changes
Looks great! Ack

2023-05-04 18:57 UTC, merged