Issue 5852 = Remove turbo mode from the code base
389ds/389-ds-base pull request #5893
Opened 2023-08-10 14:14 UTC by jchapma

Description: Turbo mode is a feature that improves the search performance for a low number of highly active connections. Since its introduction the deployment model has changed and this feature is no longer required. Turbo mode adds some complexity to the code so removal will simplify connection code.

Fix description: Following investigation into the pros/cons of turbo mode it has been decided that this feature should be removed from the codebase.

Relates: https://github.com/389ds/389-ds-base/issues/5852

Reviewed by: ?

2023-08-11 15:52 UTC, progier389 approved these changes
LGTM

2023-08-13 23:11 UTC, Firstyear requested changes
I love PR's that delete lots of code like this :)

2023-08-13 23:11 UTC, Firstyear commented on ldap/servers/slapd/connection.c
> +                PRIntervalTime timeout = PR_MillisecondsToInterval(100);
Probably should be a constant for future tweaking.

2023-08-16 13:34 UTC, vashirov commented
I had turbo mode turned off in dse.ldif. After I updated packages, my instance refused to start:
```
Aug 16 09:31:59 rhel93 ns-slapd[5820]: [16/Aug/2023:09:31:59.487554556 -0400] - ERR - dse_read_one_file - The entry cn=config in file /etc/dirsrv/slapd-localhost/dse.ldif (lineno: 10) is invalid, error code 1 (Operations error) - Setting of nsslapd-enable-turbo-mode attribute is currently disabled, it will be removed in the future
```
I think we should not make this an error, but rather WARN or INFO, and not prevent DS from starting.

2023-08-17 17:05 UTC, tbordaz reviewed
Nice code. Few comments/questions

2023-08-17 17:05 UTC, tbordaz commented on ldap/servers/slapd/connection.c
> +        int32_t ioblocktimeout_waits = conn->c_ioblocktimeout;
My understanding is that ioblocktimeout_waits is a count of the number of wait, not a duration. So we should set it to the number of time we 'waits_done'.

This is why it divides ioblocktimeout by CONN_TURBO_TIMEOUT_INTERVAL and sleep for CONN_TURBO_TIMEOUT_INTERVAL.

2023-08-17 17:05 UTC, tbordaz commented on ldap/servers/slapd/connection.c
> -        if ((ret == CONN_DONE) || (ret == CONN_TIMEDOUT)) {
This block is just logging debug info regarding the connection. It logs info about turbo mode, that should be removed,  but the rest of the message looks good to me.

2023-08-17 17:05 UTC, tbordaz commented on ldap/servers/slapd/connection.c
> -                    conn->c_idlesince = curtime;
Why removing update of idlesince ? There are more data on the socket so it looks to me we can update idlesince.

2023-08-31 22:08 UTC, jchapma commented
The nsslapd-enable-turbo-mode attribute will remain in the code for a short while, the user will be able to get the attr value and will receive an info message when trying to replace its value.

In the initial commit, I return error code 1 (operations error) when the user tries to replace the attr value, which will issue an info message to the user. But, in the corner case where the user has upgraded DS, instance restart explodes while loading dse.ldif (https://github.com/389ds/389-ds-base/pull/5893#issuecomment-1680617793)

So instead, I return success when the user tries to replace the attr value and I have added the attr type to reject_attr_type() in configdse.c. This way I can issue a message to the user when a replace is attempted and maintain dse compatibility. 

What do you think ?

2023-10-25 12:46 UTC, tbordaz commented
A performance issue was found with the replication total init testcase (see https://github.com/389ds/389-ds-base/issues/5761). Additional tests during that investigation, focus on turbo mode impact. It is looking turbo mode was beneficial.
A possibility is that a randomly selected worker, was picking up the first entry of the total update and because of the constant flow of new entries, its turns into a listener/worker (thanks to turbo mode) and finally applies many/all the operations of the total init.

It would be interesting to verify turbo-mode removal on total init

2023-10-25 12:58 UTC, jchapma commented
> A performance issue was found with the replication total init testcase (see #5761). Additional tests during that investigation, focus on turbo mode impact. It is looking turbo mode was beneficial. A possibility is that a randomly selected worker, was picking up the first entry of the total update and because of the constant flow of new entries, its turns into a listener/worker (thanks to turbo mode) and finally applies many/all the operations of the total init.
> 
> It would be interesting to verify turbo-mode removal on total init

I agree, following our discussion yesterday it seems like turbo mode could play a part, well for a total init anyway. I will open a ticket to investigate this.

2023-10-25 13:09 UTC, progier389 commented
> I agree, following our discussion yesterday it seems like turbo mode could play a part, well for a total init anyway. I will open a ticket to investigate this.
FYI: In yesterday tests, I have seen that after disabling the turbo mode, during total update the average operation optime and wtime increased (but not the time between start and end of the total update session.   
  That said the database was quite small (around 550 entries) but it will probably worth to redo the test with 100K or 1M entries  )

2023-12-31 16:11 UTC, tbordaz commented
Another thing to clarify is that bind/accept slowness when turbo mode is 'on'. (see solution 4292701). ATM it is not clear to me why it is slower, possibly the consequence a long computation to switch on/off turbo mode.
So AFAIK, this PR requires verification of 'total init' (https://github.com/389ds/389-ds-base/pull/5893#issuecomment-1779199586) and long accept/bind

2026-03-26 20:37 UTC, jchapma commented
This ticket has been around for a while now and we have no plans to remove turbo mode in the near future. Closing this ticket for now. If there are any request for this we can re-open this ticket.

2026-03-26 20:37 UTC, closed without merging