update replication.py
389ds/389-ds-base pull request #5934
Opened 2023-09-21 06:49 UTC by strzh

https://github.com/389ds/389-ds-base/pull/5930
as @progier389 @tbordaz  sugguested, change the related code in the replication.py

2023-09-21 09:18 UTC, progier389 approved these changes
The changes look good. 
Thanks for the contribution !
But you should also create the issue associated with PR 
   (In your case, the important part is the one that describes step by step how you reproduce the bug) 
(FYI: The issue will be helpful later on for:
   - the quality engineer that test the bug is fixed in a given release
   - the bug documentation
   -  tracking the eventual cherry-pick in other branches
 )

2023-09-21 11:55 UTC, strzh commented
> The changes look good. Thanks for the contribution ! But you should also create the issue associated with PR (In your case, the important part is the one that describes step by step how you reproduce the bug) (FYI: The issue will be helpful later on for:
> 
> * the quality engineer that test the bug is fixed in a given release
> * the bug documentation
> * tracking the eventual cherry-pick in other branches
>   )

Hi, created related issue https://github.com/389ds/389-ds-base/issues/5935

2023-09-21 23:24 UTC, droideck requested changes
I have a doubt about the change...
Do we really need to introduce another parameter for compatibility when it's just a simple bug?

I think we can leave `--passwd-file` as it is and use its value for `repl_manager_password`.

2023-09-22 08:25 UTC, progier389 commented
HI @droideck, In fact that was the original idea in the first PR but both Thierry and me were thinking it is better to have a consistent interface (when looking at the other argparse option in  replica.py it is always named bind-password-file.)
I would simply have added an alias but IMHO the way it is done here as the merit of being more clear.

2023-10-05 21:50 UTC, droideck approved these changes
Okay, if no one objects beside me, I agree with the majority. Ack!

2023-10-13 11:07 UTC, merged