Issue 6172 - RFE: improve the performance of evaluation of filter com…
389ds/389-ds-base pull request #6173
Opened 2024-05-15 10:00 UTC by tbordaz

…ponent when tested against a large valueset (like group members)

Bug description:
Before returning an entry (to a SRCH) the server checks that the entry matches the SRCH filter. If a filter component (equality) is testing the value (ava) against a large valueset (like uniquemember values), it takes a long time because of large number of value and required normalization of the values. This can be improved taking benefit of sorted valueset. Those sorted valueset were created to improve updates of large valueset (groups) but not used in SRCH path.

Fix description:
if config param 'nsslapd-filter-match-use-sorted-vs = on' then it uses slapi_valueset_find (that tries to use sorted valueset) rather than plugin_call_syntax_filter_ava.
In both case sorted valueset and plugin_call_syntax_filter_ava, ava and values are normalized.
In sorted valueset, the values have been normalized to insert the index in the sorted array and then comparison is done on normalized values. In plugin_call_syntax_filter_ava, all values in valuearray (of valueset) are normalized before comparison.

Likely this optimization should be dropped for extended search

relates: #6172

Reviewed by:

2024-05-15 10:46 UTC, progier389 requested changes
The idea of using directly the valueset is good.
but it can only be done if  ftype == LDAP_FILTER_EQUALITY 
and in this case I do not think that using yet another config parameter is really needed (in 389ds, equality is implement by comparing normalized values anyway)
That said, IMHO we should also write some CI tests for that one:
  - to check the scenario you describe 
  - and also a scenario storing data on a case ignore string attribute then  searching  for uppercase then for lowercase  (To double check that the filter values are properly normalized)

2024-05-15 17:11 UTC, progier389 approved these changes
Looks good except a minor point: 
I would change the "else" comment to something easier to understand, for example:
When sorted valuearray optimization cannot be used lets filter the value according to its syntax"

2024-05-15 19:37 UTC, droideck approved these changes
Looks good

2024-05-16 07:28 UTC, tbordaz commented
@progier389 , @droideck , Thanks for the review. I will update the patch accordingly in addition with a testcase I am working on.

2024-05-17 14:02 UTC, tbordaz commented
I added a testcase to the patch

2024-05-22 09:29 UTC, merged