Issue 6441 - Add basic dsidm posixgroup tests
389ds/389-ds-base pull request #6449
Opened 2024-12-16 13:23 UTC by mirielka

New basic dsidm posixgroup test - create, list, get, get_dn, modify, rename, rename with keep-old-rdn option.

Relates: https://github.com/389ds/389-ds-base/issues/6441

Author: Lenka Doudova

Reviewed by: ???

2024-12-17 02:17 UTC, droideck requested changes
Couple of minor issue, but overall - looks great!

2024-12-17 02:17 UTC, droideck commented on dirsrvtests/tests/suites/clu/dsidm_posixgroup_test.py
> +def test_dsidm_group_get_dn(topology_st, create_test_group):
Probably, it makes sense to rename the test function to `test_dsidm_posixgroup_get_dn` for consistency

2024-12-17 02:17 UTC, droideck commented on dirsrvtests/tests/suites/clu/dsidm_posixgroup_test.py
> +    assert new_posixgroup.exists()
I think we should also check that the group has previously specified `args.gidNumber = '3000'`

2024-12-17 02:17 UTC, droideck commented on dirsrvtests/tests/suites/clu/dsidm_posixgroup_test.py
> +                    'objectClass: nsMemberOf']
Alignment

2024-12-17 08:18 UTC, mirielka commented
Thanks for review, fixes pushed

2024-12-17 19:34 UTC, mirielka commented
Added fix for failing get_dn option.

2024-12-19 00:59 UTC, droideck approved these changes
Looks good! Ack

2024-12-19 09:47 UTC, merged