Issue 6417 - (2nd) If an entry RDN is identical to the suffix, then E…
389ds/389-ds-base pull request #6460
Opened 2024-12-20 11:33 UTC by tbordaz

…ntryrdn gets broken during a reindex

Bug description:
	The primary fix has a flaw as it assumes that the
	suffix ID is '1'.
	If the RUV entry is the first entry of the database
	the server loops indefinitely

Fix description:
	Read the suffix ID from the entryrdn index

fixes: #6417

Reviewed by: Pierre Rogier (reviewed the first fix)

2025-01-02 14:01 UTC, progier389 requested changes

2025-01-02 14:01 UTC, progier389 commented on ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c
> +    ID suffix_id;
Style: We usually initialize the variable at declaration time. 
 ID suffix_id = 1;

2025-01-02 14:01 UTC, progier389 commented on ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c
> +
Memory leak: I think that both
```
dblayer_value_free(be, &data);
dblayer_value_free(be, &key);
```
are needed (whether rc==0 or not)

2025-01-02 17:36 UTC, tbordaz commented on ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c
> +
Nice catch. Thanks.
I updated the fix

2025-01-06 12:26 UTC, progier389 approved these changes
LGTM

2025-01-06 13:00 UTC, merged